server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 503321xx
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
debug: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml




